replicaCount: 1

image:
  repository: devaasirvatham/devops-app
  tag: "25956797404"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: devops-app.local
      paths:
        - path: /
          pathType: Prefix


